<?php

namespace AppBundle\Repository;

/**
 * EntidadeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EntidadeRepository extends \Doctrine\ORM\EntityRepository
{
}
